USE [master]
GO

/****** Object:  Database [valeMercaderia_Dimak]    Script Date: 26-10-2023 3:32:18 ******/
DROP DATABASE [valeMercaderia_Dimak]
GO

/****** Object:  Database [valeMercaderia_Dimak]    Script Date: 26-10-2023 3:32:18 ******/
CREATE DATABASE [valeMercaderia_Dimak]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'valeMercaderia_Dimak', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\valeMercaderia_Dimak.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'valeMercaderia_Dimak_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\valeMercaderia_Dimak_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [valeMercaderia_Dimak].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [valeMercaderia_Dimak] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [valeMercaderia_Dimak] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [valeMercaderia_Dimak] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [valeMercaderia_Dimak] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [valeMercaderia_Dimak] SET ARITHABORT OFF 
GO

ALTER DATABASE [valeMercaderia_Dimak] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [valeMercaderia_Dimak] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [valeMercaderia_Dimak] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [valeMercaderia_Dimak] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [valeMercaderia_Dimak] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [valeMercaderia_Dimak] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [valeMercaderia_Dimak] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [valeMercaderia_Dimak] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [valeMercaderia_Dimak] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [valeMercaderia_Dimak] SET  DISABLE_BROKER 
GO

ALTER DATABASE [valeMercaderia_Dimak] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [valeMercaderia_Dimak] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [valeMercaderia_Dimak] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [valeMercaderia_Dimak] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [valeMercaderia_Dimak] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [valeMercaderia_Dimak] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [valeMercaderia_Dimak] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [valeMercaderia_Dimak] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [valeMercaderia_Dimak] SET  MULTI_USER 
GO

ALTER DATABASE [valeMercaderia_Dimak] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [valeMercaderia_Dimak] SET DB_CHAINING OFF 
GO

ALTER DATABASE [valeMercaderia_Dimak] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [valeMercaderia_Dimak] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [valeMercaderia_Dimak] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [valeMercaderia_Dimak] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [valeMercaderia_Dimak] SET QUERY_STORE = ON
GO

ALTER DATABASE [valeMercaderia_Dimak] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [valeMercaderia_Dimak] SET  READ_WRITE 
GO

